name: Update pre-commit hooks

on:
  schedule:
    # Every monday at 7 AM
    - cron: 0 7 * * 1
  # on demand
  workflow_dispatch:

permissions:
  contents: write  # Minimum permission required to push changes and create a pull request

jobs:
  autoupdate-precommit:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          check-latest: true

      # Step 3: Install pre-commit
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit

      # Step 4: Autoupdate pre-commit hooks
      - name: Autoupdate pre-commit hooks
        run: |
          pre-commit autoupdate

      # Step 5: Commit updated hooks (if changes exist)
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .pre-commit-config.yaml
          git commit -m "Update pre-commit hooks" || echo "No changes to commit"

      # Step 6: Create Pull Request
      - name: Create pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pre-commit-autoupdate
          title: "chore(deps): Update pre-commit hooks"
          commit-message: "chore(deps): Update pre-commit hooks"
          labels: dependencies
          delete-branch: True
          body: |
            This PR updates the pre-commit hooks using `pre-commit autoupdate`.

            - Automated by GitHub Actions.
