name: Update pre-commit hooks

on:
  schedule:
    # Every monday at 7 AM
    - cron: 0 7 * * 1
  # on demand
  workflow_dispatch:

permissions:
  contents: write  # This permission is required to push commits to a branch.
  issues: write # Manage issues (create, edit, label, comment, close). label in this case
  pull-requests: write # This permission is required to create or update pull requests.

jobs:
  autoupdate-precommit:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          check-latest: true

      # Step 3: Install pre-commit
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
          python -m pip install sync-pre-commit-deps

      # Step 4: Autoupdate pre-commit hooks
      - name: Autoupdate pre-commit hooks
        run: |
          pre-commit autoupdate

      # Step 5: sync-pre-commit-deps
      - name: Update additional dependencies after pre-commit autoupdate
        run: |
          sync-pre-commit-deps .pre-commit-config.yaml || echo "Updates found, but continuing.. avoiding Exit code 1 for CI/CD"

      # Step 6: Commit updated hooks (if changes exist)
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .pre-commit-config.yaml
          git commit -m "Update pre-commit hooks" || echo "No changes to commit"

      # Step 7: Create Pull Request
      - name: Create pull-request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pre-commit-autoupdate
          title: "chore(deps): Update pre-commit hooks"
          commit-message: "chore(deps): Update pre-commit hooks"
          labels: dependencies
          delete-branch: True
          body: |
            This PR updates the pre-commit hooks using `pre-commit autoupdate`.

            - Automated by GitHub Actions.

      # Step 8: Auto-merge PR (if created)
      - name: Auto-merge PR (squash)
        if: steps.cpr.outputs.pull-request-url != ''
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = Number(process.env.PR_NUMBER);
            const commitTitle = `🔀 Auto-squash merge for PR #${prNumber}`;
            const commitMessage = `This PR was automatically merged using squash by GitHub Actions.`;

            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash',
              commit_title: commitTitle,
              commit_message: commitMessage,
            });
        env:
          PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
